### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by wei** [piskyscan/dns_over_tls_over_tor#1]
Requesting docker support. Thank you!

**Comment by piskyscan** [comment]
Have added a Dockerfile.  Let me know how you get on.  Its my first Dockerfile so it may not be very good.
It creates a secure DNS server on 8053 so you will still have to point your main DNS server to it.

**Comment by wei** [comment]
Appreciate the help, can you explain what this is about?

https://github.com/piskyscan/dns_over_tls_over_tor/blob/62dd42e3961f47277368f4c57e69adc9ea96a957/run_stubby.sh#L8

**Comment by piskyscan** [comment]
If something disastrous goes wrong and the command line instantly fails its stops the machine thrashing at 100% CPU.  (Suppose you make a mistake in a config file for instance).

The command should never return (unless it crashes) so that code shouldnt get hit.
