### ISSUE TITLE
dig timing out 

### ISSUE THREAD

**Issue by habsfanongit** [piskyscan/dns_over_tls_over_tor#2]
Hi,
I am getting the following when I try dig @127.0.0.1 -using the specified port 8053 after modifying stubby.yml
```
dig @127.0.0.1 -p 8053 google.com

; <<>> DiG 9.10.3-P4-Raspbian <<>> @127.0.0.1 -p 8053 google.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```
I did install stubby from the source code using https://gist.github.com/FrankSantoso/f8a5f658e43c96ed244550f370ad2b95 (mentioned in the Reddit link).

**Comment by piskyscan** [comment]
Sorry for the delay, didnt see this.

I think you may have installed stubby as the DNS server on port 53.
Try sudo netstat -tpln and see what is listening on port 53 and 8053.

**Comment by habsfanongit** [comment]
Thanks, I will look into that this weekend and post back to you

**Comment by piskyscan** [comment]
Closed.
